version: "2"
services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nest_crud_db
      MYSQL_USER: user
      MYSQL_PASSWORD: HogeFuga911
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

volumes:
  mysql:
    driver: local